name: Notify Slack

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mapping file
        uses: actions/checkout@v3

      - name: Map GitHub user to Slack ID
        id: slackmap
        run: |
          GITHUB_USER="${{ github.actor }}"
          SLACK_ID=$(jq -r --arg user "$GITHUB_USER" '.[$user]' slack_mapping.json)
          if [ "$SLACK_ID" == "null" ]; then
            SLACK_ID=$GITHUB_USER
          fi
          echo "slack_id=$SLACK_ID" >> $GITHUB_OUTPUT

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "🚀 Workflow triggered by ${{ github.actor }} (${ { steps.slack_id.outputs.slack_id }})"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
