name: Use Prerequisites

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person running the workflow'
        required: false
        default: 'GitHub User'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: rajatsaini1/github-action-centralised-prerequisites/workflows@main
