name: Notify Slack

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mapping file
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-python-app .

      # Run tests inside Docker and generate junit xml report
      - name: Run tests in Docker
        run: |
          mkdir -p reports
          docker run --rm -v ${{ github.workspace }}/reports:/app/reports my-python-app

      # Send Slack notification
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": ":rocket: Workflow *${{ github.workflow }}* completed",
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
                  "title": "GitHub Action Result",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Branch",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "${{ job.status }}",
                      "short": true
                    },
                    {
                      "title": "Actor",
                      "value": "${{ github.actor }}",
                      "short": true
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Map GitHub user to Slack ID
        id: slackmap
        run: |
          GITHUB_USER="${{ github.actor }}"
          SLACK_ID=$(jq -r --arg user "$GITHUB_USER" '.[$user]' slack_mapping.json)
          if [ "$SLACK_ID" == "null" ]; then
            SLACK_ID=$GITHUB_USER
          fi
          echo "slack_id=$SLACK_ID" >> $GITHUB_OUTPUT

      - name: Send Slack notification
        run: |
          SLACK_ID=${{ steps.slackmap.outputs.slack_id }}
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\":rocket: Workflow triggered by <@$SLACK_ID>\"}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}
