name: Notify Slack

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mapping file
        uses: actions/checkout@v3

      - name: Map GitHub user to Slack ID
        id: slackmap
        run: |
          GITHUB_USER="${{ github.actor }}"
          SLACK_ID=$(jq -r --arg user "$GITHUB_USER" '.[$user]' slack_mapping.json)
          if [ "$SLACK_ID" == "null" ]; then
            SLACK_ID=$GITHUB_USER
          fi
          echo "slack_id=$SLACK_ID" >> $GITHUB_OUTPUT

      - name: Send Slack notification
        run: |
          SLACK_ID=${{ steps.slackmap.outputs.slack_id }}
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\":rocket: Workflow triggered by <@$SLACK_ID>\"}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}
